baseURL: "https://zaniniasia.netlify.app" # todo: change site url.
title: Zanini # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.svg # todo: add your custom logo to static/
  subtitle: Alfred Zanini is a Hong Kong-based filmmaker. # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Alfred Zanini # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio: # defines how many columns / projects it will show
    columns:
      desktop:
        default: 3
        archive: 6
      mobile:
        default: 2
        archive: 3
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:alfred@zanini.asia'
      landing: true
    - icon: 'fab fa-gitlab fa-lg'
      url: 'https://gitlab.com/zalfie'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/zalfie_photo/'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/alfred-z-981465153/'
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
    - stock
    - photos
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: true
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: photos
      url: /photos/
      weight: 2
    - name: stock
      url: /stock/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
